modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/eatAWESOME/PixelmonExchange/issues"
license="MIT"

[[mods]]
  modId="projecte"
  version="${version}"
  displayName="PixelmonExchange"
  displayURL="https://github.com/eatAWESOME/PixelmonExchange"
  logoFile="logo.png"
  authors="Alden Tilley"
  credits="EE2 creator - x3n0ph0b3, EE2 GUI Textures - MidnightLightning, Former Texture Artist - Magic Banana, Project E Developers - SinKillerJ, MaPePeR, williewillus, Lilylicious, pupnewfster"
  description='''A fork of ProjectE with a focus on Pixelmon'''

[[dependencies.projecte]]
  modId="minecraft"
  mandatory=true
  versionRange="${mc_version}"
  side="BOTH"
[[dependencies.projecte]]
  modId="forge"
  mandatory=true
  versionRange="${forge_version}"
  side="BOTH"
[[dependencies.projecte]]
  modId="crafttweaker"
  mandatory=false
  versionRange="${crafttweaker_version}"
  ordering="AFTER"
  side="BOTH"
[[dependencies.projecte]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1,)"
    ordering="NONE"
    side="BOTH"